#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

# Modified for Kevin Green's needs

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# my beloved key mappings!
xmodmap ~/.Xmodmap

# System startup applications
gnome-screensaver &
xfce4-power-manager
pulseaudio --start --log-target=syslog

# Personal startup applications
~/.fehbg

# Tray icons
nm-applet &

gnome-session &
