#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

# Modified for Kevin Green's needs

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Start the system tray
# tray &
#exec trayer --edge top --align right --widthtype pixel --width 200 --SetDockType true --SetPartialStrut true --transparent false -alpha 0 --tint 0x000000 --expand true --heighttype pixel --height 16 &

# use xfce's power manager
xfce4-power-manager &

# my beloved key mappings!
xmodmap ~/.Xmodmap

# Start screensaver
gnome-screensaver &

# Start sound server
pulseaudio --start --log-target=syslog &

# An emacs daemon for global org capture
emacs --daemon=global-org-capture

google-chrome &

gnome-session &
