#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

# Modified for Kevin Green's needs

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Configure X
xsetroot -cursor_name left_ptr &
xrdb -merge ~/.Xdefaults &

# my beloved key mappings!
xmodmap ~/.Xmodmap

# Start a window compositor. This ensures Google Chrome paints correctly.
xcompmgr -n &

# Start the system tray
tray &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi

# Start screensaver
gnome-screensaver &

# Start sound server
pulseaudio --start --log-target=syslog &

gnome-session &
